---
version: 2
plan:
  project-key: TKP
  key: NODE3434
  name: node_test

variables:
  NODELABEL: "master"  # Default value; Bamboo does not dynamically set nodes
  ENV: "dev"  # Default environment value
  TEST: "false"  # Default test trigger value

stages:
  - Build

jobs:
  - job:
      key: PRINT_VALUES
      name: Print Values Job
      agent:
        image: 'your-docker-image'  # Specify Docker image if needed
      tasks:
        - script:
            interpreter: SHELL
            scripts:
              - |
                echo "Trigger CI: ${bamboo.TEST}"
                echo "Environment: ${bamboo.ENV}"
                echo "Node name: ${bamboo.NODELABEL}"

        - manual:
            description: "Trigger CI tests"
            enabled: "${bamboo.TEST}" == "true"
            tasks:
              - script:
                  interpreter: SHELL
                  scripts:
                    - echo "Running CI tests..."

triggers:
  - repository:
      type: polling
      pollingStrategy: PERIODIC
      interval: '5'

parameters:
  - name: ENV
    type: choice
    default: "dev"
    options: ["dev", "prod"]
    description: "Environment selection"

  - name: TEST
    type: boolean
    default: false
    description: "Trigger CI tests"
