---
version: 2
plan:
  project-key: TKP
  key: test54
  name: test_pipeline

stages:
  - stage:
      name: Build
      jobs:
        - job:
            key: BUILD
            name: Build Job
            agent:
              image: 'your-docker-image'  # Replace with a specific Docker image if needed
            requirements:
              - key: 'your-agent-requirements'  # Define specific agent requirements if necessary

            tasks:
              - script:
                  - echo "Job Name: ${bamboo.buildPlanName}"
                  - echo "Branch Name: ${bamboo.planRepository.branch}"
                  - echo "GIT Committer: ${bamboo.repository.git.username}"  # Adjust if variables differ
                  - echo "GIT Author: ${bamboo.repository.git.author}"  # Adjust if variables differ

              - artifact-download:
                  name: Your Artifact Name
                  destination: "./"  # Adjust as needed

triggers:
  - repository:  # This triggers builds on repository changes
      type: polling
      pollingStrategy: PERIODIC
      interval: '5'  # Check for changes every 5 minutes

variables:
  branch_name: "${bamboo.planRepository.branch}"  # Define any additional needed variables
  token: 'test_token'  # Adjust your secret token as needed
